=== MartiHui/GSDAM_EjercicioAccesoDatos/XML (Old)/ListaOrdenesReply.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT ServicioTecnicoMoviles (head, body)>
	<!ELEMENT head (action)>
		<!ELEMENT action (#PCDATA)>
	<!ELEMENT body (ordenes)>
		<!ELEMENT ordenes (orden*)>
			<!ELEMENT orden (id, modelo, fecha, estado, reparaciones)>
				<!ELEMENT id (#PCDATA)>
				<!ELEMENT modelo (#PCDATA)>
				<!ELEMENT fecha (#PCDATA)>
				<!ELEMENT estado (#PCDATA)>
				<!ELEMENT reparaciones (reparacion+)>
					<!ELEMENT reparacion (nombre, precio)>
						<!ELEMENT nombre (#PCDATA)>
						<!ELEMENT precio (#PCDATA)>

=== MartiHui/GSDAM_EjercicioAccesoDatos/XML/ListaOrdenesReply.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ServicioTecnicoMoviles SYSTEM "ListaOrdenesReply.dtd">
<ServicioTecnicoMoviles>
	<head>
		<action>LISTA_ORDENES_ASK</action>
	</head>
	<body>
		<ordenes>
			<orden>
				<id></id>
				<modelo></modelo>
				<fecha></fecha>
				<estado></estado>
				<reparaciones>
					<reparacion>
						<nombre></nombre>
						<precio></precio>
					</reparacion>
				</reparaciones>
			</orden>
		</ordenes>
	</body>
</ServicioTecnicoMoviles>
