=== MartiHui/GSDAM_EjercicioAccesoDatos/XML (Old)/ReparacionInfoReply.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT ServicioTecnicoMoviles (head)>
	<!ELEMENT head (action)>
		<!ELEMENT action (#PCDATA)>
	<!ELEMENT body (modelo_id, reparaciones)>
        <!ELEMENT modelo_id (#PCDATA)>
		<!ELEMENT reparaciones (reparacion*)>
			<!ELEMENT reparacion (nombre, tiempo, coste)>
				<!ATTLIST reparacion id CDATA #REQUIRED>
				<!ELEMENT nombre (#PCDATA)>
				<!ELEMENT tiempo (#PCDATA)>
				<!ELEMENT coste (#PCDATA)>

=== MartiHui/GSDAM_EjercicioAccesoDatos/XML/ReparacionInfoReply.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ServicioTecnicoMoviles SYSTEM "ReparacionInfoReply.dtd">
<ServicioTecnicoMoviles>
    <head>
        <action>REPARACION_INFO_REPLY</action>
    </head>
    <body>
    	<reparaciones>
    		<reparacion id="">
    			<nombre></nombre>
    			<tiempo></tiempo>
    			<coste></coste>
    		</reparacion>
    	</reparaciones>
    </body>
</ServicioTecnicoMoviles>

=== MartiHui/GSDAM_EjercicioAccesoDatos/XML (Old)/ReparacionInfoReply.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ServicioTecnicoMoviles SYSTEM "ReparacionInfoReply.dtd">
<ServicioTecnicoMoviles>
    <head>
        <action>REPARACION_INFO_REPLY</action>
        <ask result="">
    </head>
    <body>
        <modelo_id></modelo_id>
    	<reparaciones>
    		<reparacion id="">
    			<nombre></nombre>
    			<tiempo></tiempo>
    			<coste></coste>
    		</reparacion>
    	</reparaciones>
    </body>
</ServicioTecnicoMoviles>
